### ISSUE TITLE
Task | March 4 | 6am

### ISSUE THREAD

**Issue by rkpatra201** [learning-project-01/bookstore-app#88]
1. [Merge 2 sorted arrays without using Extra space.] Write JUNIT.
2. Design database for an appointment booking application. Design and Share using https://dbdiagram.io/

**Comment by Ansu-s** [comment]
- For the array sort, I swapped the elements in the array by checking if the last element of the first array is smaller than the first element of the second array if not I swapped them and iterated through the array doing this swap so that the first array contain all the small elements and the second array contain all the larger elements and then I sorted them so the elements are arranged. The program is [here](https://github.com/Ansu-s/active-tasks/blob/main/dsa-examples/src/main/java/MergeSortedArrays.java)  

- For the Database design I learned DBML. I learned how to create tables, define keys,constraints and how to add relations 
by using the foreign keys. Database design for appointment booking system is [here](https://dbdiagram.io/d/Appointment-booking-application-65e4c366cd45b569fb679a2c)
